export * from '../global.js'
export * from './getData.js'
export * from '../product_detail/productMenuBar.js';
export * from '../product_detail/acordian.js';
export * from '../product_detail/popupBtn.js';
export * from '../product_detail/placeHolder.js';
export * from '../product_detail/reviewPost.js';
export * from './clickEvents.js';
export * from '../global.js';